/* eslint-disable react/no-unescaped-entities */
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

//components
import DesktopNavbar from "../components/DesktopNavbar"
import Footer from "../components/Footer"
import Container from "../components/Container"
import styled from 'styled-components'

const PrivacyPolicyPage = styled.div`
    background: url(/images/background.png);
    overflow:hidden;
    background-size: 500px;
    background-position: center;
    background-repeat: none;
    @media (max-width: 1024px) {
        border: none;
        background-size: 500px;
    }
    @media (max-width: 550px) {
        border: none;
        background-size: 300px;
    }
`
const TextContainer = styled.div`
padding-top:60px;
`
const Headings = styled.h1`
font-weight: 600;
font-size: 30px;
line-height: 36px;
padding-bottom: 32px;
`
const Paragraph = styled.p`
font-weight: 300;
font-size: 18px;
line-height: 36px;
`
const Paragraphlist = styled.li`
font-weight: 300;
font-size: 18px;
line-height: 36px;
list-style: disc;
list-style-position: inside;
margin-left:20px;
`
const Mesh = styled.div`
    width: 724px;
    height: 650px;
    position: absolute;
    left: 50%;
    top:400px;
    transform: translate(-50%, -50%);
    opacity: 0.14;
    background: radial-gradient(36.28% 36.28% at 50% 50%, #FD8AFD 0%, rgba(222, 28, 28, 0) 100%),
    radial-gradient(36.28% 36.28% at 50% 50%, rgba(41, 39, 160, 0.26) 0%, rgba(41, 39, 160, 0) 100%),
    radial-gradient(36.28% 36.28% at 50% 50%, rgba(201, 129, 56, 0.47) 0%, rgba(255, 202, 148, 0) 100%);
    @media (max-width: 1024px) {
      top:400px;
    }
    @media (max-width: 550px) {
      top: 400px;
      width: 382px;
      height: 442px;
    }
`
export default function privacypolicy () {
  return (
    <div className='font-body'>
        <Head>
            <title>Web3Media Privacy Policy</title>
            <meta
            name="description"
            content="Empowering and providing financial freedom for web3 designers, artists, blockchain talents, and creative minds"/>
            <link rel="icon" href="/images/logo.svg" />

                    <meta property="og:type" content="website" />
        <meta property="og:url" content="https://web3d.media" />
        <meta property="og:title" content="Web3D Media Privacy Policy" />
        <meta property="og:description" content="Empowering and providing financial freedom for web3 designers, artists, blockchain talents, and creative minds" />
        <meta property="og:image" content="/images/meta-image.jpg" />

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="https://web3d.media" />
        <meta property="twitter:title" content="Web3D Media Privacy Policy" />
        <meta property="twitter:description" content="Empowering and providing financial freedom for web3 designers, artists, blockchain talents, and creative minds"/>
        <meta property="twitter:image" content="/images/meta-image.jpg"></meta>
        </Head>

        <DesktopNavbar></DesktopNavbar>

        <PrivacyPolicyPage className='text-b4 pt-32'>
            <div className='px-8 pt-8 md:px-24 lg:px-48'>
                <div className='flex'>
                    <Link href='/legal'>
                        <a>
                            <h1 className='underline text-lg'>Home </h1>
                        </a>
                    </Link>
                    <h1 className='text-b4 text-lg'>/ Privacy policy</h1>
                </div>

                <Mesh></Mesh>
                <div className='pt-20'>
                    <h1 className='text-6xl font-bold'>Privacy Policy</h1>
                    <p className='text-xl text-b5 pt-8 pb-20'>Updated at 2022-04-28</p>
                    <Paragraph>Web3D Media (“we,” “our,” or “us”) is committed to protecting your privacy. 
                    This Privacy Policy explains how your personal information is collected, used, and disclosed by Web3D Media.
                    This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) 
                    alongside our application, Web3D Media. By accessing or using our Service, you signify that you have read,
                    understood, and agree to our collection, storage, use, and disclosure of your personal information as described 
                    in this Privacy Policy and our Terms of Service.</Paragraph>
                </div>

                <TextContainer>
                    <Headings>Definitions and key terms</Headings>
                    <Paragraph>
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms
                    are referenced, are strictly defined as:
                
                    <ul>
                    <Paragraphlist>Cookie: small amount of data generated by a website and saved by your web browser.It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information. </Paragraphlist>
                    <Paragraphlist>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Web3D Media Incorporated, 651 N Broad Street Suite 206 Middletown de 19709, New Castle, Delaware that is responsible for your information under this Privacy Policy. </Paragraphlist>
                    <Paragraphlist>Country: where Web3D Media or the owners/founders of Web3D Media are based, in this case is United States. </Paragraphlist>
                    <Paragraphlist>Customer: refers to the company, organization or person that signs up to use the Web3D Media Service to manage the relationships with your consumers or service users. </Paragraphlist>
                    <Paragraphlist>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Web3D Media and use the services. </Paragraphlist>
                    <Paragraphlist>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet. </Paragraphlist>
                    <Paragraphlist>Personnel: refers to those individuals who are employed by Web3D Media or are under contract to perform a service on behalf of one of the parties. </Paragraphlist>
                    <Paragraphlist>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person. </Paragraphlist>
                    <Paragraphlist>Service: refers to the service provided by Web3D Media as described in the relative terms (if available) and on this platform. </Paragraphlist>
                    <Paragraphlist>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. </Paragraphlist>
                    <Paragraphlist>Website: Web3D Media's site, which can be accessed via this URL: https://web3d.media/ </Paragraphlist>
                    <Paragraphlist>You: a person or entity that is registered with Web3D Media to use the Services. </Paragraphlist>
                    </ul>
                </Paragraph>
            </TextContainer>

            
            <TextContainer>
                <Headings>What Information Do We Collect</Headings>
                <Paragraph>We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.</Paragraph>
                <ul>
                    <Paragraphlist>Name / Username</Paragraphlist>
                        <Paragraphlist>Phone Numbers</Paragraphlist>
                        <Paragraphlist>Email Addresses</Paragraphlist>
                        <Paragraphlist>Mailing Addresses</Paragraphlist>
                        <Paragraphlist>Age</Paragraphlist>
                        <Paragraphlist>Password</Paragraphlist>
                </ul>
            </TextContainer>

            <TextContainer>
                <Headings>What Information Do We Collect</Headings>
                <Paragraph>Any of the information we collect from you may be used in one of the following ways:</Paragraph>

                <ul>
                    <Paragraphlist>To personalize your experience (your information helps us to better respond to your individual needs)</Paragraphlist>
                    <Paragraphlist>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</Paragraphlist>
                    <Paragraphlist>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs) To process transactions</Paragraphlist>
                    <Paragraphlist>To administer a contest, promotion, survey or other site feature</Paragraphlist>
                    <Paragraphlist>To send periodic emails</Paragraphlist>
                </ul>
            </TextContainer>

            <TextContainer>
                <Headings>How Do We Use The Information We Collect?</Headings>
                <Paragraph>Any of the information we collect from you may be used in one of the following ways:</Paragraph>
                <ul>
                    <Paragraphlist>To personalize your experience (your information helps us to better respond to your individual needs)</Paragraphlist>
                    <Paragraphlist>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</Paragraphlist>
                    <Paragraphlist>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs) To process transactions</Paragraphlist>
                    <Paragraphlist>To administer a contest, promotion, survey or other site feature</Paragraphlist>
                    <Paragraphlist>To send periodic emails</Paragraphlist>
                </ul>
            </TextContainer>

            <TextContainer>
                <Headings>When does Web3D Media use end user information from third parties?</Headings>
                <Paragraph>Web3D Media will collect End User Data necessary to provide the Web3D Media services to our customers.</Paragraph>
                <Paragraph className='py-8'></Paragraph>
                <Paragraph>End users may voluntarily provide us with information they have made available on social media websites. If you provide us with any such information, we may collect publicly available information from the social media websites you have indicated. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</Paragraph>
            </TextContainer>
            
            <TextContainer>
                <Headings>When does Web3D Media use customer information from third parties?</Headings>
                <Paragraph>We receive some information from the third parties when you contact us. For example, when you submit your email address to us to show interest in becoming a Web3D Media customer, we receive information from a third party that provides automated fraud detection services to Web3D Media. We also occasionally collect information that is made publicly available on social media websites. You can control how much of your information social media websites make public by visiting these websites and changing your privacy settings.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Do we share the information we collect with third parties?</Headings>
                <Paragraph>
                    We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.
                    <Paragraph className='py-8'></Paragraph>
                    We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.
                    <Paragraph className='py-8'></Paragraph>
                    We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website in a shared location, and type of the device used to visit the website. They may aggregate information about our advertising and what you see on the website and then provide auditing, research and reporting for us and our advertisers. We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.
                </Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Where and when is information collected from customers and end users?</Headings>
                <Paragraph>Web3D Media will collect personal information that you submit to us. We may also receive personal information about you from third parties as described above.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>How Do We Use Your Email Address?</Headings>
                <Paragraph>By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>How Do We Protect Your Information?</Headings>
                <Paragraph>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Web3D Media or guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our physical, technical, or managerial safeguards.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Could my information be transferred to other countries?</Headings>
                <Paragraph>Web3D Media is incorporated in United States. Information collected via our website, through direct interactions with you, or from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any of the above, you voluntarily consent to the trans-border transfer and hosting of such information.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Is the information collected through the Web3D Media Service secure?</Headings>
                <Paragraph>We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes, make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Can I update or correct my information?</Headings>
                <Paragraph>The rights you have to request updates or corrections to the information Web3D Media collects depend on your relationship with Web3D Media. Personnel may update or correct their information as detailed in our internal company employment policies.
                Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.
                You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.
                If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Personnel</Headings>
                <Paragraph>If you are a Web3D Media worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.
                You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you.
                Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Sale of Business</Headings>
                <Paragraph>We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of Web3D Media or any of its Corporate Affiliates (as defined herein), or that portion of Web3D Media or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Affiliates</Headings>
                <Paragraph>We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with Web3D Media, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Governing Law</Headings>
                <Paragraph>
                    This Privacy Policy is governed by the laws of United States without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.
                    <Paragraph className='py-8'></Paragraph>
                    The laws of United States, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.
                    <Paragraph className='py-8'></Paragraph>
                    By using Web3D Media or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.
                </Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Your consent</Headings>
                <Paragraph>We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Privacy Policy and agree to its terms.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Links to Other Websites</Headings>
                <Paragraph>This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled by Web3D Media. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any other
                website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Advertising</Headings>
                <Paragraph>
                This website may contain third party advertisements and links to third party sites. Web3D Media does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.
                <Paragraph className='py-8'></Paragraph>
                Advertising keeps Web3D Media and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.
                <Paragraph className='py-8'></Paragraph>
                Third party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by Web3D Media of the third party sites, goods or services. Web3D Media takes no responsibility for the content of any of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.</Paragraph>
            </TextContainer>
            
            <TextContainer>
                <Headings>Cookies for Advertising</Headings>
                <Paragraph>These cookies collect information over time about your online activity on the website and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many clicks they received.</Paragraph>
            </TextContainer>
            
            <TextContainer>
                <Headings>Cookies</Headings>
                <Paragraph>Web3D Media uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Blocking and disabling cookies and similar technologies</Headings>
                <Paragraph>Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.</Paragraph>
            </TextContainer>
            
            <TextContainer>
                <Headings>Remarketing Services</Headings>
                <Paragraph>We use remarketing services. What Is Remarketing? In digital marketing, remarketing (or retargeting) is the practice of serving ads across the internet to people who have already visited your website. It allows your company to seem like they're “following” people around the internet by serving ads on the websites and platforms they use most.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Kids' Privacy</Headings>
                <Paragraph>We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Changes To Our Privacy Policy</Headings>
                <Paragraph>We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Third-Party Services</Headings>
                <Paragraph>
                We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").
                <Paragraph className='py-8'></Paragraph>
                You acknowledge and agree that Web3D Media shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Web3D Media does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.
                <Paragraph className='py-8'></Paragraph>
                Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Tracking Technologies</Headings>
                <ul>
                    <Paragraphlist>Google Maps API <br/>
                    Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup just to name a few.
                    Google Maps API may collect information from You and from Your Device for security purposes.
                    Google Maps API collects information that is held in accordance with its Privacy Policy</Paragraphlist>
                    <Paragraph className='py-8'></Paragraph>
                    <Paragraphlist>Cookies <br/>
                    We use Cookies to enhance the performance and functionality of our website but are non-essential to their use. However,
                    without these cookies, certain functionality like videos may become unavailable or you would be required to enter your
                    login details every time you visit the website as we would not be able to remember that you had logged in previously.</Paragraphlist>
                    <Paragraph className='py-8'></Paragraph>
                    <Paragraphlist>Sessions <br/>
                    Web3D Media uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.</Paragraphlist>
                </ul>
            </TextContainer>

            <TextContainer>
                <Headings>Information about General Data Protection Regulation (GDPR)</Headings>
                <Paragraph>We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under protection from being replicated or used in the wrong way.</Paragraph>
            </TextContainer>
            
            <TextContainer>
                <Headings>What is personal data?</Headings>
                <Paragraph>
                    Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP addresses, physical address, sexual orientation, and ethnicity.
                    <Paragraph className='py-8'></Paragraph>
                    The Data Protection Principles include requirements such as:
                    <ul>
                        <Paragraphlist>Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.</Paragraphlist>
                        <Paragraphlist>Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.</Paragraphlist>
                        <Paragraphlist>Personal data should be held no longer than necessary to fulfil its purpose.</Paragraphlist>
                        <Paragraphlist>People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.</Paragraphlist>
                    </ul>

                </Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Why is GDPR important?</Headings>
                <Paragraph>GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond these facts it's simply the right thing to do. At Web3D Media we strongly believe that your data privacy is very important and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Individual Data Subject's Rights - Data Access, Portability and Deletion</Headings>
                <Paragraph>We are committed to helping our customers meet the data subject rights requirements of GDPR. Web3D Media processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days.
                We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>California Residents</Headings>
                <Paragraph>The California Consumer Privacy Act (CCPA) requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
                <Paragraph className='py-8'></Paragraph>
                We are also required to communicate information about rights California residents have under California law. You may exercise the following rights:
                <ul>
                    <Paragraphlist>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</Paragraphlist>
                    <Paragraphlist>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</Paragraphlist>
                    <Paragraphlist>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</Paragraphlist>
                    <Paragraphlist>Request that a business that sells a consumer's personal data, not sell the consumer's personal data.</Paragraphlist>
                </ul>
                <Paragraph className='py-8'></Paragraph>
                If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
                <Paragraph className='py-8'></Paragraph>
                We do not sell the Personal Information of our users.
                <Paragraph className='py-8'></Paragraph>
                For more information about these rights, please contact us.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>California Online Privacy Protection Act (CalOPPA)</Headings>
                <Paragraph>CalOPPA requires us to disclose categories of Personal Information we collect and how we use it, the categories of sources from whom we collect Personal Information, and the third parties with whom we share it, which we have explained above.
                <Paragraph className='py-8'></Paragraph>
                CalOPPA users have the following rights:
                <ul>
                    <Paragraphlist>Right to Know and Access. You may submit a verifiable request for information regarding the: (1) categories of Personal Information we collect, use, or share; (2) purposes for which categories of Personal Information are collected or used by us; (3) categories of sources from which we collect Personal Information; and (4) specific pieces of Personal Information we have collected about you.</Paragraphlist>
                    <Paragraphlist>Right to Equal Service. We will not discriminate against you if you exercise your privacy rights.</Paragraphlist>
                    <Paragraphlist>Right to Delete. You may submit a verifiable request to close your account and we will delete Personal Information about you that we have collected.</Paragraphlist>
                    <Paragraphlist>Right to request that a business that sells a consumer's personal data, not sell the consumer's personal data.</Paragraphlist>
                </ul>
                <Paragraph className='py-8'></Paragraph>
                If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
                <Paragraph className='py-8'></Paragraph>
                We do not sell the Personal Information of our users.
                <Paragraph className='py-8'></Paragraph>
                For more information about these rights, please contact us.</Paragraph>
            </TextContainer>

            <TextContainer>
                <Headings>Contact Us</Headings>
                <Paragraph>
                    Don't hesitate to contact us if you have any questions.
                    <ul>
                        <Paragraphlist>
                            Via Email: <a href="mailto:hello@web3d.media">hello@web3d.media</a>
                        </Paragraphlist>
                    </ul>
                </Paragraph>
            </TextContainer>

         </div>

         

        </PrivacyPolicyPage>

        <Container>
            <Footer></Footer>
        </Container>
    </div>
  )
}
